### ISSUE TITLE
Redirect the Index page

### ISSUE THREAD

**Issue by sannon** [GovLab/GovLab.org-Site#16]
Can we get the below redirection set up? The first link is what shows up in google searches etc.

http://thegovlab.org/govlab-index/  
redirect to
http://thegovlab.org/observatory/the-govlab-index/ 

Thank you!

**Comment by luisdaniel** [comment]
There is no way to remove "observatory" from that URL since that page is listed under "The Observatory" parent category.

**Comment by sannon** [comment]
Nope, not what I meant -- I don't want to remove "observatory" from the
URL.

This specific URL needs to redirect to the observatory URL:
http://thegovlab.org/govlab-index/

If you click it, you'll see it currently goes to a weirdly formatted page.

On Tue, Nov 18, 2014 at 1:56 PM, Luis notifications@github.com wrote:

> There is no way to remove "observatory" from that URL since that page is
> listed under "The Observatory" parent category.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GovLab/GovLab.org-Site/issues/16#issuecomment-63524486
> .

## 

_Shruti H. Sannon_
Research Associate, The GovLab
Master of Arts in Media, Culture, and Communication, 2014
New York University
646-708-4447  | shruti.sannon@gmail.com

**Comment by luisdaniel** [comment]
Redirecting is an involved process, potentially dangerous, and sets a dangerous precedent (soon everyone will want their link redirected, then we'll have the issue of keeping track of what redirects where). 
_Changing_ the URL would've been much easier, but it can't be done.

However:
Your initial problem is that the /govlab-index/ link is ranked first by google. This is because of meta tags, page content, and other SEO stuff. If you redirect the link, google will eventually flip the search results and you'll end up with your original problem.

Instead of doing this redirect workaround, fix the SEO of your page. Click Edit Page and there is a section on SEO at the bottom of the Edit Page page. Fill that form out with the appropriate tags and meta information, then click Update. The change will not be immediate. You'll have to wait until Google re-scans our site and re-indexes the page. I have no idea how long this would take.
