### ISSUE TITLE
Feb 2 book event on site

### ISSUE THREAD

**Issue by elh266** [GovLab/GovLab.org-Site#24]
Could we please add the Feb 3 event to the site?

Claudio's flier with info here: https://drive.google.com/file/d/0B2aJDpN60H7nRXFTb2M0TVIzM28/view?usp=sharing

**Comment by elh266** [comment]
Oh and, there should be a separate standalone page and it should be in the landing page carousel. Thanks!

**Comment by luisdaniel** [comment]
ask Claudio about standalone page because I don't know what format they want or where they even want this thing to live. 

I can add a banner-thing to the carousel, but I need a banner (the flier is not a banner). Major difference is the size. That flier does not fit as is on the carousel on the front page.

**Comment by claudioccm** [comment]
Standalone link - hosted in Mailchimp. This is a standard feature in mailchimp. Can be accessed by the "View this message in you browser" on the top of the emails. - http://eepurl.com/bbOugT

And here is the banner for the slider.
![banner-monroe-price](https://cloud.githubusercontent.com/assets/1649373/5825769/e9d6552a-a0bb-11e4-9273-c7e04a8de789.jpg)

**Comment by luisdaniel** [comment]
Thanks. 
Done. Banner on front slider with link.
